import { Router } from "express";
import { prisma } from "../../db.js";
import { requireAuth, requireRole } from "../../middleware/auth.js";
const router = Router();
const ACTIVE = ["WAITING","CALLED","CHECKED_IN","SERVING"];
const TOKEN_SELECT={id:true,tokenNumber:true,status:true,position:true,generatedAt:true,calledAt:true,checkedInAt:true,serviceStartedAt:true,currentStageId:true,user:{select:{id:true,name:true,phoneNumber:true}}};
const eta=({ahead,busy,capacity,baseline})=>Math.max(0,Math.ceil((ahead+busy)/Math.max(1,capacity))*Math.max(1,baseline||10));
router.get("/summary",requireAuth,requireRole("STAFF","ADMIN"),async(req,res)=>{try{const sw=req.user.role==="ADMIN"?{}:{officeId:req.user.officeId};const stages=await prisma.serviceStage.findMany({where:{service:sw},select:{id:true,serviceId:true,stageOrder:true,nameEn:true,nameNe:true,baselineMinutes:true,counters:{where:{isActive:true},select:{id:true,currentTokenId:true}},service:{select:{id:true,nameEn:true,nameNe:true,officeId:true,office:{select:{id:true,nameEn:true,nameNe:true}}}}},orderBy:[{serviceId:"asc"},{stageOrder:"asc"}]});const ids=stages.map(s=>s.id);const ts=ids.length?await prisma.token.findMany({where:{currentStageId:{in:ids},status:{in:ACTIVE}},select:{currentStageId:true,status:true,stageEnteredAt:true}}):[];const by=new Map();for(const t of ts){const c=by.get(t.currentStageId)||{waiting:0,called:0,checkedIn:0,serving:0,oldest:null};c[t.status.toLowerCase()]=(c[t.status.toLowerCase()]||0)+1;if(t.status==="WAITING"&&(!c.oldest||t.stageEnteredAt<c.oldest))c.oldest=t.stageEnteredAt;by.set(t.currentStageId,c)}const svc=new Map();for(const st of stages){const c=by.get(st.id)||{waiting:0,called:0,checkedIn:0,serving:0,oldest:null};const busy=c.called+c.checkedIn+c.serving;const entry={id:st.id,stageOrder:st.stageOrder,nameEn:st.nameEn,nameNe:st.nameNe,capacity:st.counters.length,counts:{waiting:c.waiting||0,called:c.called||0,checkedIn:c.checkedIn||0,serving:c.serving||0},longestWaitMinutes:c.oldest?Math.floor((Date.now()-new Date(c.oldest).getTime())/60000):0,estimatedNextWaitMinutes:c.waiting?eta({ahead:0,busy,capacity:st.counters.length,baseline:st.baselineMinutes}):0};if(!svc.has(st.serviceId))svc.set(st.serviceId,{id:st.service.id,nameEn:st.service.nameEn,nameNe:st.service.nameNe,officeId:st.service.officeId,office:st.service.office,stages:[]});svc.get(st.serviceId).stages.push(entry)}return res.json({success:true,services:[...svc.values()]})}catch(e){console.error(e);return res.status(500).json({success:false,message:"Failed to load queue summary"})}});
router.get("/:stageId",requireAuth,requireRole("STAFF","ADMIN"),async(req,res)=>{try{const stage=await prisma.serviceStage.findFirst({where:{id:req.params.stageId,service:req.user.role==="ADMIN"?undefined:{officeId:req.user.officeId}},include:{service:{select:{id:true,nameEn:true,nameNe:true,officeId:true,office:{select:{id:true,nameEn:true,nameNe:true}}}},counters:{where:{isActive:true},select:{id:true,name:true,currentTokenId:true}}}});if(!stage)return res.status(403).json({success:false,message:"You are not assigned to this government office"});const [serving,called,waiting,skipped]=await Promise.all([prisma.token.findMany({where:{currentStageId:stage.id,status:"SERVING"},select:TOKEN_SELECT,orderBy:{serviceStartedAt:"asc"}}),prisma.token.findMany({where:{currentStageId:stage.id,status:"CALLED"},select:TOKEN_SELECT,orderBy:{calledAt:"asc"}}),prisma.token.findMany({where:{currentStageId:stage.id,status:"WAITING"},select:TOKEN_SELECT,orderBy:[{stageEnteredAt:"asc"},{generatedAt:"asc"},{id:"asc"}]}),prisma.token.findMany({where:{currentStageId:stage.id,status:"SKIPPED",generatedAt:{gte:new Date(Date.now()-2*60*60*1000)}},select:TOKEN_SELECT,orderBy:{generatedAt:"desc"},take:20})]);
const skippedUserIds=[...new Set(skipped.map(t=>t.user?.id).filter(Boolean))];
const replacementTokens=skippedUserIds.length?await prisma.token.findMany({where:{userId:{in:skippedUserIds},serviceId:stage.serviceId,status:{in:ACTIVE}},select:{id:true,userId:true,tokenNumber:true,status:true},orderBy:{generatedAt:"desc"}}):[];
const replacementByUser=new Map();
for(const t of replacementTokens){if(!replacementByUser.has(t.userId))replacementByUser.set(t.userId,t);}
const recentlySkipped=skipped.map(t=>{const replacement=replacementByUser.get(t.user?.id);return {...t,recallable:!replacement,activeReplacementToken:replacement?{id:replacement.id,tokenNumber:replacement.tokenNumber,status:replacement.status}:null};});
const busy=serving.length+called.length;return res.json({success:true,stage,queue:{serving,called,waiting:waiting.map((t,i)=>({...t,position:i+1,estimatedWaitMinutes:eta({ahead:i,busy,capacity:stage.counters.length,baseline:stage.baselineMinutes})})),recentlySkipped},capacity:stage.counters.length})}catch(e){console.error(e);return res.status(500).json({success:false,message:"Failed to load stage queue"})}});
export default router;
